# Generated by Django 2.2.25 on 2022-01-27 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20220127_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercourse',
            name='teacher',
            field=models.ForeignKey(help_text="Select your 'username'!", on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=256)),
                ('desc', models.TextField()),
                ('number_of_questions', models.IntegerField(default=1)),
                ('time', models.IntegerField(default='10', help_text='Duration of the quiz in seconds')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='teachers.TeacherCourse')),
            ],
        ),
    ]
